name: caso2
services:
  back:
    image: ${REGISTRY_URL}/${NOMBRE_GRUPO}/${NOMBRE_PROYECTO}/back
    container_name: back
    build:
      context: ./backend
      target: production
    environment:
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=${PGHOST}
      - FRONTEND_URL=${FRONTEND_URL}
  front:
    image: ${REGISTRY_URL}/${NOMBRE_GRUPO}/${NOMBRE_PROYECTO}/front
    container_name: front
    build:
      context: ./frontend
      target: production
      args:
        - FRONTEND_URL=${FRONTEND_URL}
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
  base:
    image: ${REGISTRY_URL}/${NOMBRE_GRUPO}/${NOMBRE_PROYECTO}/base
    container_name: base
    build:
      context: ./database
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
  proxy:
    image: nginx:alpine
    container_name: proxy
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - ./proxy/myconf.template:/etc/nginx/templates/default.conf.template
      - ./proxy/certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - front
      - back